# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - release
notifications:
  email: false
sudo: false
addons:
  apt_packages:
    - libgmp-dev #for building glpk
before_install:
  - pip install --user xlrd
  - julia -e "Pkg.add(\"GLPKMathProgInterface\")"
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("urbs"); Pkg.test("urbs"; coverage=true)'
